version: '3.8'

services:
  real-time-data-service:
    container_name: real-time-data-service
    image: ${DOCKER_USERNAME}/real-time-data-service:latest
    ports:
      - "8100:8100"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true