server:
  port: 8100
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: real-time-data-service
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html